AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  GetLogs:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetLogs
      Runtime: nodejs18.x
      Handler: index.handler
      InlineCode: |
        exports.handler = async (event) => {
          return {
            statusCode: 200,
            body: JSON.stringify({ message: "Log list" }),
          };
        };
Outputs:
  GetLogs:
    Value: !GetAtt GetLogs.Arn