openapi: 3.0.1
info:
  title: HTTPApi
  version: 1.0.0
security:
  - CognitoAuthorizer: []
paths:
  /orders:
    get:
      responses:
        '200':
          description: Success
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ ApiGwExecutionRole, Arn ]
        uri:
          Fn::Sub: ${GetOrders}
        httpMethod: POST
        payloadFormatVersion: "2.0"
        type: aws_proxy
  /logs:
    get:
      responses:
        '200':
          description: Success
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ ApiGwExecutionRole, Arn ]
        uri:
          Fn::Sub: ${GetLogs}
        httpMethod: POST
        payloadFormatVersion: "2.0"
        type: aws_proxy

components:
  securitySchemes:
    CognitoAuthorizer:
      type: oauth2
      name: Authorization
      in: header