AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  GetOrders:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetOrders
      Runtime: nodejs18.x
      Handler: index.handler
      InlineCode: |
        exports.handler = async (event) => {
          return {
            statusCode: 200,
            body: JSON.stringify({ message: "Order list" }),
          };
        };
Outputs:
  GetOrders:
    Value: !GetAtt GetOrders.Arn