version = 0.1
[default.deploy.parameters]
stack_name = "sam-nested"
s3_bucket = "sam-nested-template"
region = "us-east-1"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
image_repositories = []
