AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  AuthStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: auth.yaml
  OrderStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: order.yaml
  LogStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: log.yaml
  ApiStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: api.yaml
      Parameters:
        GetOrders: !GetAtt OrderStack.Outputs.GetOrders
        GetLogs: !GetAtt LogStack.Outputs.GetLogs
        UserPoolId: !GetAtt AuthStack.Outputs.UserPoolId
        UserPoolClientId: !GetAtt AuthStack.Outputs.UserPoolClientId

Outputs:
  HttpApiUrl:
    Value: !GetAtt ApiStack.Outputs.HttpApiUrl